const mongoose = require('mongoose');
const User = require('./models/User');

mongoose.connect('mongodb://localhost:27017/tshirt_store')
    .then(() => console.log('MongoDB Connected for Seeding'))
    .catch(err => console.error(err));

const users = [
    { fullName: "Sanjay Hiralal Buchiya", tshirtName: "SANJU", size: "L", mobile: "7069803539" },
    { fullName: "Buchiya vishal k", tshirtName: "Vishal", size: "XXL", mobile: "7990704762" },
    { fullName: "Vinay lalji buchiya", tshirtName: "Vinay buchiya", size: "L", mobile: "8141368022" },
    { fullName: "બુચિયા પ્રવીણ લખમશી", tshirtName: "Pravin", size: "M", mobile: "6353007755" },
    { fullName: "PRAKASH", tshirtName: "PRAKASH", size: "M", mobile: "7567709787" },
    { fullName: "Buchiya Anil Govindbhai", tshirtName: "ANIL", size: "XL", mobile: "9687323586" },
    { fullName: "Buchiya mukesh thavar bhai", tshirtName: "MukeshSinh", size: "L", mobile: "9879388594" },
    { fullName: "Buchiya navin Jamnadash", tshirtName: "N J", size: "M", mobile: "7359896867" },
    { fullName: "Buchiya Chetan Devji", tshirtName: "C D", size: "L", mobile: "7567449927" },
    { fullName: "PRAYAAN", tshirtName: "PRAYAAN (Nanu balak chhe number -12)", size: "S/30", mobile: "8980401868" },
    { fullName: "Prakash Premji", tshirtName: "PBHURO", size: "M", mobile: "8980401868" },
    { fullName: "Anil Devshi Buchiya", tshirtName: "ANNU", size: "L", mobile: "9327393257" },
    { fullName: "Buchiya karan shivji bhai", tshirtName: "Karan", size: "L", mobile: "9316652472" },
    { fullName: "Buchiya Prakash Lalji", tshirtName: "Prakash", size: "M", mobile: "8347976694" },
    { fullName: "Buchiya Rohit velji bhai", tshirtName: "Rohit", size: "M", mobile: "9978737170" },
    { fullName: "Buchiya kantilal khimji", tshirtName: "KANTI", size: "XXL", mobile: "9979058886" },
    { fullName: "Buchiya Tushar Dhanji", tshirtName: "Tushar Buchiya", size: "XXL", mobile: "6354070001" },
    { fullName: "Buchiya Hiren", tshirtName: "H_K_MARU_", size: "XL", mobile: "9909718757" },
    { fullName: "SAGAR BUCHIYA", tshirtName: "SAGAR", size: "M", mobile: "7046621656" },
    { fullName: "BUCHIYA BHARAT DAYLAL", tshirtName: "Bharat", size: "XL", mobile: "7069575666" },
    { fullName: "BUCHIYA SAGAR DEVSHI", tshirtName: "SAGAR", size: "M", mobile: "6354389393" },
    { fullName: "BUCHIYA HARDIK", tshirtName: "HARDIK", size: "M", mobile: "6354389393" },
    { fullName: "BUCHIYA NAVIN DEVSHI", tshirtName: "NAVIN", size: "XL", mobile: "6354389393" },
    { fullName: "Meet Buchiya", tshirtName: "Meet", size: "L", mobile: "9327058065" },
    { fullName: "Buchiya badal ravilal", tshirtName: "Badal", size: "XL", mobile: "9328516771" },
    { fullName: "Buchiya viram manji bhai", tshirtName: "Viram", size: "XXL", mobile: "8140733268" },
    { fullName: "Chetan c buchiya", tshirtName: "Chetan", size: "M", mobile: "7203834740" },
    { fullName: "buchiya bhavesh kanji", tshirtName: "BK", size: "L", mobile: "6351640401" },
    { fullName: "BUCHIYA BHAVESH GOVIND", tshirtName: "BHAVESH", size: "L", mobile: "9687485932" },
    { fullName: "Buchiya Bhavik kantilal", tshirtName: "Bhavik", size: "S", mobile: "9537041322" },
    { fullName: "MukeshKumar Sayabhai Buchiya", tshirtName: "  શ્રી", size: "XXL", mobile: "9978397716" },
    { fullName: "Buchiya Nikhil Rajesh", tshirtName: "NIKHU", size: "L", mobile: "8160994172" },
    { fullName: "Buchiya vishal parsotambhai", tshirtName: "V. P", size: "L", mobile: "9328934270" },
    { fullName: "Buchiya bipin.R", tshirtName: "BIPIN", size: "M", mobile: "9904012845" },
    { fullName: "Buchiya mansukh bhimjibhai", tshirtName: "THE MB", size: "L", mobile: "7567448167" },
    { fullName: "BUCHIYA SURESH KARAMSHI", tshirtName: "SURESH", size: "L", mobile: "9913033537" },
    { fullName: "BUCHIYA TARUN SURESH K", tshirtName: "TARUN", size: "S/32", mobile: "9913033537" },
    { fullName: "Shaan maru", tshirtName: "Shaan maru", size: "M", mobile: "9023958874" },
    { fullName: "Vipul Khimji Buchiya", tshirtName: "Vipul", size: "XL", mobile: "8238560760" },
    { fullName: "Buchiya krishna vipul", tshirtName: "Krishna", size: "XL", mobile: "8238560760" },
    { fullName: "Buchiya prakash dayalal", tshirtName: "Prakash", size: "XL", mobile: "9054198090" },
    { fullName: "Buchiya prath kumar ramesh .26 .no tshirt", tshirtName: "Prath", size: "S/26", mobile: "9054198090" },
    { fullName: "BUCHIYA SACHIN LAKHAMSHI", tshirtName: "SACHIN", size: "M/36", mobile: "9099490428" },
    { fullName: "Buchiya shanti lakha", tshirtName: "S.L", size: "M", mobile: "8141561163" },
    { fullName: "Buchiya darshan n", tshirtName: "Darshan", size: "L", mobile: "9510602519" },
    { fullName: "BUCHIYA SURESH KARSHAN", tshirtName: "SURESH", size: "XXXL", mobile: "9979063360" },
    { fullName: "Buchiya Prince Naranbhai", tshirtName: "Prince", size: "L", mobile: "9913842186" },
    { fullName: "Buchiya vishal lalji", tshirtName: "Vishal", size: "M", mobile: "7984454856" },
    { fullName: "BUCHIYA KANTILAL", tshirtName: "Kanti..", size: "XL", mobile: "9979058886" },
    { fullName: "Buchiya Ram", tshirtName: "Ram", size: "M", mobile: "8141387839" },
    { fullName: "Buchiya parsotambhai veljibhai", tshirtName: "P. V", size: "XXL", mobile: "9913838797" },
    { fullName: "BUCHIYA AJAY DAYALAL", tshirtName: "AJAY", size: "XXXL", mobile: "9023034981" },
    { fullName: "BUCHIYA JAYESH DAYALAL", tshirtName: "JAYESH", size: "L", mobile: "8238761910" },
    { fullName: "Kudecha chetan devji bhai", tshirtName: "Chetan", size: "XXL", mobile: "9687929755" },
    { fullName: "Buchiya Bharat Magan", tshirtName: "B.M", size: "L", mobile: "8980397768" },
    { fullName: "Buchiya Shanti Magan", tshirtName: "S.M", size: "XL", mobile: "9316390728" },
    { fullName: "Jitendra thavar bhai buchiya", tshirtName: "Jitendra", size: "XXL", mobile: "9726536348" },
    { fullName: "Haresh thavar bhai buchiya", tshirtName: "Haresh", size: "XXL", mobile: "8799275593" },
    { fullName: "Hitesh thavar bhai buchiya", tshirtName: "Hitesh", size: "XL", mobile: "87992755993" },
    { fullName: "BUCHIYA DHANJI BHAI THAVAR", tshirtName: "DHANJI", size: "XXL", mobile: "9687502283" },
    { fullName: "Ravi Jerambhai Buchiya", tshirtName: "Ravi", size: "XL", mobile: "7574064694" },
    { fullName: "Buchiya Kaushik kanji", tshirtName: "Kaushik", size: "XS/34", mobile: "8238379783" },
    { fullName: "Buchiya meet kanji", tshirtName: "Meet", size: "XS/34", mobile: "8238379783" },
    { fullName: "MAHESH KHIMJI BUCHIYA", tshirtName: "M B", size: "XL", mobile: "8238560760" },
    { fullName: "Buchiya nitin l", tshirtName: "Nitin", size: "M", mobile: "9327582593" },
    { fullName: "Gopal magan buchiya", tshirtName: "G M BUCHIYA", size: "XXL", mobile: "7984231053" },
    { fullName: "Buchiya dev l", tshirtName: "Dev", size: "XL", mobile: "9016972682" },
    { fullName: "Buchiya dipak khimji", tshirtName: "Dipak", size: "XXL", mobile: "9265420381" },
    { fullName: "Buchiya Rupesh Ravij bhai", tshirtName: "Rupshii", size: "XL", mobile: "9727144848" },
    { fullName: "Odhana vinay devjibhai", tshirtName: "Vinay", size: "L", mobile: "8200715150" },
    { fullName: "Buchiya chetan lakhamshi", tshirtName: "Chetan.L", size: "L", mobile: "9327825889" },
    { fullName: "BHARAT", tshirtName: "BHARAT", size: "L", mobile: "8141733350" },
    { fullName: "NARSHI SUMARBHAI BUCHIYA", tshirtName: "N S BUCHIYA", size: "XL", mobile: "9081331411" },
    { fullName: "Lalji Khimji Buchiya", tshirtName: "Lalji K B", size: "M", mobile: "8469720020" },
    { fullName: "Odhana dhruv laljibhai", tshirtName: "Dhruv", size: "L", mobile: "9727580591" },
    { fullName: "Hitesh Arvindbhai Buchiya", tshirtName: "H B", size: "XXL", mobile: "6359964525" },
    { fullName: "Buchiya Lakhan Jamnadash", tshirtName: "Lakhan", size: "M", mobile: "7359896867" },
    { fullName: "Buchiya Mitesh Aravind", tshirtName: "Meet Maru", size: "XL", mobile: "9512358700" },
    { fullName: "Buchiya kanti nanji", tshirtName: "MR BUCHIYA", size: "XL", mobile: "8154013482" },
    { fullName: "BUCHIYA RIYANSH MOHAN", tshirtName: "RIYANSH", size: "S/28", mobile: "9099490428" },
    { fullName: "Buchiya Raj kanji bhai", tshirtName: "Raju", size: "M", mobile: "9601709617" },
    { fullName: "Buchiya akash kanji bhai", tshirtName: "Akash", size: "M", mobile: "9825634652" },
    { fullName: "Buchiya shanti chapshi", tshirtName: "S.C.MARU", size: "XL", mobile: "8141380085" },
    { fullName: "Rajesh buchiya", tshirtName: "Rajesh buchiya", size: "L", mobile: "9979452585" },
    { fullName: "Buchiya Gautam khanaji", tshirtName: "G.K.MARU", size: "XL", mobile: "9726222463" },
    { fullName: "Buchiya Prince Mohanbhai", tshirtName: "P.M.Buchiya", size: "M", mobile: "7359355850" },
    { fullName: "Brijesh Kudecha", tshirtName: "Brijesh", size: "L", mobile: "9428065521" },
    { fullName: "Jagdish f Buchiya", tshirtName: "Jagdish", size: "L", mobile: "7984361621" },
    { fullName: "Buchiya Navin lakhabhai", tshirtName: "N L BUCHIYA", size: "6XL", mobile: "9687247799" }
];

const seedDB = async () => {
    await User.deleteMany({});
    await User.insertMany(users);
    console.log('Database Seeded');
    mongoose.connection.close();
};

seedDB();
